### ISSUE TITLE
Mandrill rejected is actually accepted

### ISSUE THREAD

**Issue by javorszky** [andris9/Nodemailer#412] opened 2015-04-05 15:09 UTC
Hi!

I'm trying to send an email without `from_address` through Mandrill. Using Nodemailer 1.3.2 and wellknown 0.1.5 for this. Authentication is good. When I send the email, the response that Nodemailer gets is `250 Ok: requeued as <id>`. Looking at the same logs in Mandrill though, it's rejected with `invalid-sender`.

I've tried to see what's going on. I see that Nodemailer's SMTP Connection decides whether this is an error or not based on the status it's getting back, which is a 2xx. Using Postman to hurl raw API at Mandrill, I'm still getting a 200 back, so I'm not actually sure this is something that's a bug in the SMTP Connection module.

See this screenshot:

![API calls](http://f.cl.ly/items/3T033z2a0a0L3i083k3t/Screen%20Shot%202015-04-05%20at%2016.07.49.png)

The HTTP status is 200, which kind of makes sense, because it DOES get back with valid data, but that's messing with all modules, and is screwing with HTTP standards.

I'm sending this ticket to Mandrill support as well in the meantime, hopefully they can weigh in what I'm doing wrong.

**Comment by andris9** [comment] 2015-04-05 19:28
If Mandrill is responding with code 250 then it means that they accepted the message. It does not yet mean that the message will be successfully sent, it just means that they accepted it, they have queued it for later processing and further delivery is now on their responsibility. What probably happens next is that they try to send out the message to the actual recipient but it fails for whatever reason. At this point the SMTP transaction with Nodemailer is long closed so they can't return the error and they log it instead. So regarding SMTP it is not a bug in Nodemailer and it is not a bug in Mandrill, it is just how SMTP works. Regarding HTTP it seems fishy but it is out of scope of Nodemailer so I can't really say much about it.

**Closed by andris9** 2015-04-05 19:28 UTC

**Comment by javorszky** [comment] 2015-04-05 19:31
That sounds sane. Thanks for the answer. I'll let you know what Mandrill got back with.

Although that said, Mandrill might need to be taken out of `nodemailer-wellknown`, and should have its own plugin due to their idiosyncrasies with handling rejections. I realise creating the plugin is also out of scope of nodemailer. Just thought leaving a note on Mandrill usage might be helpful.
